import type { ErrorCode } from "./errorCodes";
import type { MessageKey } from "./errorMessageKeys";

export const ERROR_MESSAGE_KEY_MAP: Record<ErrorCode, MessageKey> = {
  // 📦 Fetch / Lists
  DELIVERIES_FETCH_FAILED: "FETCH_FAILED",
  METRICS_FETCH_FAILED: "FETCH_FAILED",
  ORDERS_STATUS_FETCH_FAILED: "FETCH_FAILED",
  MONTHLY_ORDERS_FETCH_FAILED: "FETCH_FAILED",

  // 👥 Customers
  CUSTOMER_CREATION_FAILED: "SAVE_FAILED",
  CUSTOMER_UPDATE_FAILED: "SAVE_FAILED",
  CUSTOMER_NOT_FOUND: "NOT_FOUND",

  // 🧾 Orders
  ORDER_CREATION_FAILED: "SAVE_FAILED",
  ORDER_UPDATE_FAILED: "SAVE_FAILED",
  ORDER_NOT_FOUND: "NOT_FOUND",
  ORDER_ITEM_HAS_DELIVERY: "ORDER_LOCKED",
  ORDER_ITEM_QUANTITY_REDUCED: "ORDER_LOCKED",
  ORDER_ITEM_MISSING_PRODUCT: "NOT_FOUND",
  PRODUCT_NOT_FOUND: "NOT_FOUND",

  // 🧩 Custom Orders
  CUSTOM_ORDER_NOT_FOUND: "NOT_FOUND",
  CUSTOM_ORDER_ITEM_HAS_DELIVERY: "ORDER_LOCKED",
  CUSTOM_ORDER_ITEM_QUANTITY_REDUCED: "ORDER_LOCKED",
  CUSTOM_ORDER_ITEM_MISSING_NAME: "VALIDATION_ERROR",
  CUSTOM_ORDER_ITEM_MISSING_UNIT: "VALIDATION_ERROR",
  CUSTOM_ORDER_ITEM_CREATION_FAILED: "SAVE_FAILED",
  CUSTOM_ORDER_ITEM_UPDATE_FAILED: "SAVE_FAILED",

  // 🚚 Deliveries
  DELIVERY_CREATION_FAILED: "SAVE_FAILED",
  DELIVERY_UPDATE_FAILED: "SAVE_FAILED",
  DELIVERY_NOT_FOUND: "NOT_FOUND",
  DELIVERY_NUMBER_EXISTS: "ALREADY_EXISTS",
  DELIVERY_REMOVAL_FAILED: "DELETE_FAILED",
  CUSTOM_DELIVERY_CREATION_FAILED: "SAVE_FAILED",
  CUSTOM_DELIVERY_UPDATE_FAILED: "SAVE_FAILED",

  // ⚙️ Validation
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_ID: "VALIDATION_ERROR",

  // 🔐 Auth
  SESSION_INVALID: "SESSION_INVALID",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_NOT_FOUND: "INVALID_CREDENTIALS",
  USERNAME_EXISTS: "ALREADY_EXISTS",
  USERNAME_REQUIRED: "VALIDATION_ERROR",
  PASSWORD_REQUIRED: "VALIDATION_ERROR",
  REFRESH_TOKEN_MISSING: "SESSION_INVALID",
  AUTH_HEADER_MISSING: "UNAUTHORIZED",
  FORBIDDEN: "UNAUTHORIZED",

  // 🌐 Infra
  NETWORK_ERROR: "NETWORK_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",

  // 💱 Currency / Exchange
  CURRENCY_RATE_FETCH_FAILED: "FETCH_FAILED",
  CURRENCY_RATE_TIMEOUT: "NETWORK_ERROR",
  CURRENCY_RATE_INVALID_RESPONSE: "INTERNAL_ERROR",
  CURRENCY_RATE_NOT_FOUND: "NOT_FOUND",
};
