// src/lib/error/core/errorCodes.ts
export const ERROR_CODES = [
  // General-Dashboard
  'DELIVERIES_FETCH_FAILED',
  'METRICS_FETCH_FAILED',
  'ORDERS_STATUS_FETCH_FAILED',
  'OVERVIEW_FETCH_FAILED',

  // 👥 Customers
  'CUSTOMER_CREATION_FAILED',
  'CUSTOMER_UPDATE_FAILED',
  'CUSTOMER_NOT_FOUND',

  // 🧾 Orders
  'ORDER_CREATION_FAILED',
  'ORDER_UPDATE_FAILED',
  'ORDER_NOT_FOUND',

  'ORDER_ITEM_HAS_DELIVERY',
  'ORDER_ITEM_QUANTITY_REDUCED',
  'ORDER_ITEM_MISSING_PRODUCT',
  'ORDER_ITEM_NOT_FOUND',
  'ORDER_ITEM_INVALID',
  'DUPLICATE_ORDER_ITEM',

  // 🧩 Custom Orders
  'CUSTOM_ORDER_ITEM_HAS_DELIVERY',
  'CUSTOM_ORDER_ITEM_QUANTITY_REDUCED',
  'CUSTOM_ORDER_ITEM_MISSING_NAME',
  'CUSTOM_ORDER_ITEM_MISSING_UNIT',
  'CUSTOM_ORDER_ITEM_CREATION_FAILED',
  'CUSTOM_ORDER_ITEM_UPDATE_FAILED',
  'CUSTOM_ORDER_NOT_FOUND',

  // 🚚 Deliveries
  'DELIVERY_CREATION_FAILED',
  'DELIVERY_UPDATE_FAILED',
  'DELIVERY_NOT_FOUND',
  'DELIVERY_NUMBER_EXISTS',
  'DELIVERY_REMOVAL_FAILED',
  'INVALID_DELIVERY_QUANTITY',
  'CUSTOM_DELIVERY_CREATION_FAILED',
  'CUSTOM_DELIVERY_UPDATE_FAILED',

  // ⚙️ Validation / Stock / Input
  'INSUFFICIENT_STOCK',
  'INVALID_STOCK_QUANTITY',
  'PRODUCT_HAS_STOCK',
  'PRODUCT_NOT_FOUND',
  'VALIDATION_ERROR',
  'INVALID_ID',
  'INVALID_REFERENCE',

  'STOCK_MOVEMENT_FAILED',
  'STOCK_MOVEMENT_NOT_FOUND',
  'STOCK_MOVEMENT_DELETE_FAILED',
  'STOCK_MOVEMENT_UPDATE_FAILED',
  'RESTRICTED_STOCK_MOVEMENT',

  // 🔐 Authentication
  'UNAUTHORIZED',
  'FORBIDDEN',
  'INVALID_CREDENTIALS',
  'SESSION_INVALID',
  'USER_NOT_FOUND',
  'USERNAME_EXISTS',
  'USERNAME_REQUIRED',
  'PASSWORD_REQUIRED',
  'REFRESH_TOKEN_MISSING',
  'AUTH_HEADER_MISSING',
  'ACCOUNT_LOCKED',
  'RATE_LIMIT_EXCEEDED',

  // 🌐 Network / System
  'NETWORK_ERROR',
  'UNKNOWN_ERROR',
  'INTERNAL_ERROR',

  // 💱 Currency / Exchange
  'CURRENCY_RATE_FETCH_FAILED',
  'CURRENCY_RATE_TIMEOUT',
  'CURRENCY_RATE_INVALID_RESPONSE',
  'CURRENCY_RATE_NOT_FOUND',
] as const

export type ErrorCode = (typeof ERROR_CODES)[number]
