// src/lib/error/core/errorStatusMap.ts
import type { ErrorCode } from "./errorCodes";

export const ERROR_STATUS_MAP: Record<ErrorCode, number> = {
  // 🔐 Authentication / Session
  SESSION_INVALID: 401,
  UNAUTHORIZED: 401,
  INVALID_CREDENTIALS: 401,
  ACCOUNT_LOCKED: 423,
  RATE_LIMIT_EXCEEDED: 429,
  AUTH_HEADER_MISSING: 401,
  REFRESH_TOKEN_MISSING: 401,
  USER_NOT_FOUND: 401,

  // 🚫 Authorization
  FORBIDDEN: 403,

  // 🔍 Not found
  CUSTOMER_NOT_FOUND: 404,
  ORDER_NOT_FOUND: 404,
  DELIVERY_NOT_FOUND: 404,
  PRODUCT_NOT_FOUND: 404,
  CUSTOM_ORDER_NOT_FOUND: 404,

  // ⚙️ Validation / Domain rules
  VALIDATION_ERROR: 400,
  INVALID_ID: 400,
  USERNAME_REQUIRED: 400,
  PASSWORD_REQUIRED: 400,

  // ⚙️ Validation / Input
  ORDER_ITEM_MISSING_PRODUCT: 400,
  ORDER_ITEM_NOT_FOUND: 404,
  ORDER_ITEM_INVALID: 400,
  DUPLICATE_ORDER_ITEM: 409,
  CUSTOM_ORDER_ITEM_MISSING_NAME: 400,
  CUSTOM_ORDER_ITEM_MISSING_UNIT: 400,
  INVALID_DELIVERY_QUANTITY: 400,
  INVALID_STOCK_QUANTITY: 400,
  INVALID_REFERENCE: 400,
  STOCK_MOVEMENT_NOT_FOUND: 404,

  // ⚠️ Conflict / State
  INSUFFICIENT_STOCK: 409,
  PRODUCT_HAS_STOCK: 409,
  ORDER_ITEM_HAS_DELIVERY: 409,
  ORDER_ITEM_QUANTITY_REDUCED: 409,
  CUSTOM_ORDER_ITEM_HAS_DELIVERY: 409,
  CUSTOM_ORDER_ITEM_QUANTITY_REDUCED: 409,
  DELIVERY_NUMBER_EXISTS: 409,
  USERNAME_EXISTS: 409,
  RESTRICTED_STOCK_MOVEMENT: 409,
  CUSTOMER_HAS_ACTIVE_ORDERS: 409,

  // 🌐 Network / Infra
  NETWORK_ERROR: 503,

  // 🧨 Server
  INTERNAL_ERROR: 500,
  UNKNOWN_ERROR: 500,

  // 📦 Generic operation failures
  DELIVERIES_FETCH_FAILED: 500,
  METRICS_FETCH_FAILED: 500,
  ORDERS_STATUS_FETCH_FAILED: 500,
  OVERVIEW_FETCH_FAILED: 500,
  CUSTOMER_CREATION_FAILED: 500,
  CUSTOMER_UPDATE_FAILED: 500,
  ORDER_CREATION_FAILED: 500,
  ORDER_UPDATE_FAILED: 500,
  CUSTOM_ORDER_ITEM_CREATION_FAILED: 500,
  CUSTOM_ORDER_ITEM_UPDATE_FAILED: 500,
  DELIVERY_CREATION_FAILED: 500,
  DELIVERY_UPDATE_FAILED: 500,
  DELIVERY_REMOVAL_FAILED: 500,
  CUSTOM_DELIVERY_CREATION_FAILED: 500,
  CUSTOM_DELIVERY_UPDATE_FAILED: 500,
  STOCK_MOVEMENT_FAILED: 500,
  STOCK_MOVEMENT_DELETE_FAILED: 500,
  STOCK_MOVEMENT_UPDATE_FAILED: 500,

  // 💱 Currency / Exchange
  CURRENCY_RATE_FETCH_FAILED: 502,
  CURRENCY_RATE_TIMEOUT: 504,
  CURRENCY_RATE_INVALID_RESPONSE: 502,
  CURRENCY_RATE_NOT_FOUND: 400,
};

export function getHttpStatusFromCode(code: ErrorCode): number {
  return ERROR_STATUS_MAP[code];
}
