/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteRouteImport } from './routes/products/route'
import { Route as OrdersRouteRouteImport } from './routes/orders/route'
import { Route as DeliveriesRouteRouteImport } from './routes/deliveries/route'
import { Route as CustomersRouteRouteImport } from './routes/customers/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as DeliveriesIndexRouteImport } from './routes/deliveries/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as ProductsIdRouteImport } from './routes/products/$id'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as CustomersIdRouteImport } from './routes/customers/$id'
import { Route as ApiTestRouteImport } from './routes/api/test'
import { Route as ApiSeedRouteImport } from './routes/api/seed'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRouteRoute = OrdersRouteRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRouteRoute = DeliveriesRouteRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRouteRoute = CustomersRouteRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRouteRoute,
} as any)
const DeliveriesIndexRoute = DeliveriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeliveriesRouteRoute,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRouteRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRouteRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRouteRoute,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteRouteWithChildren
  '/deliveries': typeof DeliveriesRouteRouteWithChildren
  '/orders': typeof OrdersRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/test': typeof ApiTestRoute
  '/customers/$id': typeof CustomersIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/test': typeof ApiTestRoute
  '/customers/$id': typeof CustomersIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/customers': typeof CustomersIndexRoute
  '/deliveries': typeof DeliveriesIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/customers': typeof CustomersRouteRouteWithChildren
  '/deliveries': typeof DeliveriesRouteRouteWithChildren
  '/orders': typeof OrdersRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/test': typeof ApiTestRoute
  '/customers/$id': typeof CustomersIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/deliveries'
    | '/orders'
    | '/products'
    | '/login'
    | '/signup'
    | '/api/seed'
    | '/api/test'
    | '/customers/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/customers/'
    | '/deliveries/'
    | '/orders/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/seed'
    | '/api/test'
    | '/customers/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/customers'
    | '/deliveries'
    | '/orders'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/customers'
    | '/deliveries'
    | '/orders'
    | '/products'
    | '/_auth/login'
    | '/_auth/signup'
    | '/api/seed'
    | '/api/test'
    | '/customers/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/customers/'
    | '/deliveries/'
    | '/orders/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CustomersRouteRoute: typeof CustomersRouteRouteWithChildren
  DeliveriesRouteRoute: typeof DeliveriesRouteRouteWithChildren
  OrdersRouteRoute: typeof OrdersRouteRouteWithChildren
  ProductsRouteRoute: typeof ProductsRouteRouteWithChildren
  ApiSeedRoute: typeof ApiSeedRoute
  ApiTestRoute: typeof ApiTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRouteRoute
    }
    '/deliveries/': {
      id: '/deliveries/'
      path: '/'
      fullPath: '/deliveries/'
      preLoaderRoute: typeof DeliveriesIndexRouteImport
      parentRoute: typeof DeliveriesRouteRoute
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRouteRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRouteRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRouteRoute
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CustomersRouteRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteRouteChildren: CustomersRouteRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteRouteWithChildren = CustomersRouteRoute._addFileChildren(
  CustomersRouteRouteChildren,
)

interface DeliveriesRouteRouteChildren {
  DeliveriesIndexRoute: typeof DeliveriesIndexRoute
}

const DeliveriesRouteRouteChildren: DeliveriesRouteRouteChildren = {
  DeliveriesIndexRoute: DeliveriesIndexRoute,
}

const DeliveriesRouteRouteWithChildren = DeliveriesRouteRoute._addFileChildren(
  DeliveriesRouteRouteChildren,
)

interface OrdersRouteRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteRouteChildren: OrdersRouteRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteRouteWithChildren = OrdersRouteRoute._addFileChildren(
  OrdersRouteRouteChildren,
)

interface ProductsRouteRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteRouteChildren: ProductsRouteRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteRouteWithChildren = ProductsRouteRoute._addFileChildren(
  ProductsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CustomersRouteRoute: CustomersRouteRouteWithChildren,
  DeliveriesRouteRoute: DeliveriesRouteRouteWithChildren,
  OrdersRouteRoute: OrdersRouteRouteWithChildren,
  ProductsRouteRoute: ProductsRouteRouteWithChildren,
  ApiSeedRoute: ApiSeedRoute,
  ApiTestRoute: ApiTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
